name: ServerCore
version: 1.0
main: com.matthew.plugin.core.ServerCore
author: GoofIt
api-version: 1.8.8
commands:
  setrank:
    aliases: [rank]
  heal:
  gamemode:
    aliases: [gm]
  a:
    aliases: [admin]
  ma:
  message:
    aliases: [msg]
  reply:
    aliases: [r]
  tp:
    aliases: [teleport]
  vanish:
    aliases: [v]
  give:
  effect: